services:
  backend:
    build:
      context: ./BE
    container_name: capstone-backend
    ports:
      - "8000:8000"
    volumes:
      - ./BE:/app
    # env_file:
    #   - ./BE/.env
    restart: unless-stopped

  frontend:
    build:
      context: ./FE/web-ui
    container_name: capstone-frontend
    ports:
      - "3000:3000"
    # volumes:
    #   - ./FE:/app
    depends_on:
      - backend
    restart: unless-stopped