services:
  backend:
    build:
      context: ./BE
      target: development
    container_name: capstone-backend
    ports:
      - "8000:8000"
    volumes:
      - ./BE:/app
    env_file:
      - ./BE/.env

  backend-worker:
    build:
      context: ./BE
      target: development
    container_name: backend-worker
    command: sh -c "python manage.py qcluster"
    volumes:
      - ./BE:/app
      # cache the huggingface SentenceTransformer model
      - huggingface_cache:/root/.cache/huggingface
    env_file:
      - ./BE/.env
    depends_on:
      - backend

  frontend:
    build:
      context: ./FE/web-ui
      target: development
    container_name: capstone-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./FE/web-ui:/app
      - /app/node_modules
    depends_on:
      - backend
    environment:
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
      - INTERNAL_API_BASE_URL=http://backend:8000
