services:
  db:
    image: pgvector/pgvector:pg16 # This is the official Postgres image with pgvector pre-installed
    container_name: capstone-db
    restart: always
    environment:
      POSTGRES_USER: taskmind
      POSTGRES_PASSWORD: taskmind_password
      POSTGRES_DB: taskmind
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persists DB data
      - ./BE/init.sql:/docker-entrypoint-initdb.d/init.sql # run db initalize script

  backend:
    build:
      context: ./BE
      target: development
    container_name: capstone-backend
    ports:
      - "8000:8000"
    volumes:
      - ./BE:/app
    env_file:
      - ./BE/.env
    depends_on:
      - db
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"

  backend-worker:
    build:
      context: ./BE
      target: development
    container_name: backend-worker
    command: sh -c "python manage.py qcluster"
    volumes:
      - ./BE:/app
      # cache the huggingface SentenceTransformer model
      - huggingface_cache:/root/.cache/huggingface
    env_file:
      - ./BE/.env
    depends_on:
      - backend
      - db

  frontend:
    build:
      context: ./FE/web-ui
      target: development
    container_name: capstone-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./FE/web-ui:/app
      - /app/node_modules
    depends_on:
      - backend
    env_file:
      - ./FE/web-ui/.env.development

volumes:
  huggingface_cache:
  postgres_data:
