# Generated by Django 5.2.6 on 2026-05-21 13:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "tag",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Goal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ToDo", "ToDo"),
                            ("InProgress", "InProgress"),
                            ("Completed", "Completed"),
                            ("OnHold", "OnHold"),
                            ("Cancelled", "Cancelled"),
                            ("Overdue", "Overdue"),
                        ],
                        default="ToDo",
                        max_length=20,
                    ),
                ),
                ("deadline", models.DateField()),
                ("complete_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="goals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tag",
                    models.ManyToManyField(
                        blank=True, related_name="goals", to="goals.tag"
                    ),
                ),
            ],
            options={
                "db_table": "goal",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("deadline", models.DateField(blank=True, null=True)),
                ("complete_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ToDo", "ToDo"),
                            ("InProgress", "InProgress"),
                            ("Completed", "Completed"),
                            ("OnHold", "OnHold"),
                            ("Cancelled", "Cancelled"),
                            ("Overdue", "Overdue"),
                        ],
                        default="ToDo",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "goal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="goals.goal",
                    ),
                ),
            ],
            options={
                "db_table": "task",
                "ordering": ["deadline", "created_at"],
            },
        ),
    ]
