# Generated by Django 5.2.6 on 2026-05-21 12:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goals", "0002_alter_task_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "tag",
                "ordering": ["name"],
            },
        ),
        migrations.RemoveField(
            model_name="goal",
            name="tag",
        ),
        migrations.AddField(
            model_name="goal",
            name="tag",
            field=models.ManyToManyField(
                blank=True, related_name="goals", to="goals.tag"
            ),
        ),
    ]
