# Generated by Django 5.2.6 on 2026-05-21 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="enable_global_kb",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="enable_local_kb",
            field=models.BooleanField(default=True),
        ),
    ]
