from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status
from rest_framework.permissions import IsAuthenticated
from django.shortcuts import get_object_or_404
from django.db.models import Q
from drf_spectacular.utils import extend_schema, extend_schema_view
from django.utils import timezone
import json
import re

from .models import Goal, Task
from .services import AIGoalGeneratorService
from .serializers import (
    GoalListSerializer, 
    GoalDetailSerializer, 
    GoalCreateSerializer,
    TaskSerializer,
    GoalGenerateRequestSerializer,
    GoalGenerateResponseSerializer,
)

@extend_schema(
    tags=['Goals'], 
    auth=[],
    request=GoalGenerateRequestSerializer,
    responses={200: GoalGenerateResponseSerializer},
    summary="Generate goal with AI-powered task breakdown",
    description="Takes a goal's name, description, tag, and deadline, and returns a list of actionable tasks generated by AI."
)
class GoalBreakdownView(APIView):
    """
    API endpoint that takes a goal's name, description, tag, and deadline,
    and returns a list of actionable tasks to achieve that goal using the Groq API."""
    def post(self, request):
        name = request.data.get('name')
        description = request.data.get('description', '')
        tag = request.data.get('tag')
        deadline = request.data.get('deadline')
        files = request.FILES.getlist('files')

        if not name:
            return Response({"error": "Please provide a goal's name"}, status=status.HTTP_400_BAD_REQUEST)
        
        # if not description and not files:
        #     return Response({"error": "Please provide a description or upload files to provide context."}, status=status.HTTP_400_BAD_REQUEST)
        
        if not deadline:
            return Response({"error": "Please provide a goal's deadline"}, status=status.HTTP_400_BAD_REQUEST)

        if deadline < timezone.now().date().isoformat():
            return Response({"error": "Deadline must be a future date"}, status=status.HTTP_400_BAD_REQUEST)

        # File upload limits
        MAX_FILES = 5
        MAX_FILE_SIZE = 10 * 1024 * 1024  # 10MB per file
        ALLOWED_EXTENSIONS = ['.pdf', '.docx', '.jpg', '.jpeg', '.png', '.webp']

        if len(files) > MAX_FILES:
            return Response({"error": f"Maximum {MAX_FILES} files allowed."}, status=status.HTTP_400_BAD_REQUEST)

        for file in files:
            if file.size > MAX_FILE_SIZE:
                return Response({"error": f"File '{file.name}' exceeds the 10MB size limit."}, status=status.HTTP_400_BAD_REQUEST)
            ext = file.name.rsplit('.', 1)[-1].lower() if '.' in file.name else ''
            if f'.{ext}' not in ALLOWED_EXTENSIONS:
                return Response({"error": f"File '{file.name}' has an unsupported format. Allowed: PDF, DOCX, JPG, PNG, WebP."}, status=status.HTTP_400_BAD_REQUEST)

        # if not tag:
        #     return Response({"error": "Please provide a goal's tag"}, status=status.HTTP_400_BAD_REQUEST)

        api_key = AIGoalGeneratorService.get_api_key()
        if not api_key:
            return Response({"error": "Together AI API Key is not configured."}, status=status.HTTP_500_INTERNAL_SERVER_ERROR)
            
        # Parse context from files
        file_context = AIGoalGeneratorService.extract_context_from_files(files, api_key)
        if file_context:
            description = f"{description}\n\n[Additional Context from Files:]\n{file_context}" if description else file_context

        task_prompt = AIGoalGeneratorService.build_prompt_for_task(name, description, deadline)
        description_prompt = AIGoalGeneratorService.build_prompt_for_description(name, description, deadline)
        task_list = AIGoalGeneratorService.get_ai_response(task_prompt, api_key)

        description_response = AIGoalGeneratorService.get_ai_response(description_prompt, api_key)
        
        # FIX: Check if it is ALREADY a list before trying to parse
        if isinstance(description_response, list):
            # It's already a list, just take the first item
            if description_response:
                description = description_response[0]
            else:
                description = "" # Handle empty list case
        else:
            # It is a string, so NOW we try to parse it
            try:
                parsed_description = json.loads(description_response)
                
                if isinstance(parsed_description, list) and parsed_description:
                    description = parsed_description[0]
                else:
                    description = str(parsed_description)
                    
            except (json.JSONDecodeError, TypeError):
                # Fallback: It was just a plain string all along
                description = description_response

        try:
            result = {}
            result["name"] = name
            result["description"] = description
            result["status"] = "ToDo"
            result["deadline"] = deadline
            result["tag"] = tag
            result["completeCount"] = 0
            result["taskCount"] = len(task_list)
            result["tasks"] = task_list
            return Response(result, status=status.HTTP_200_OK)
        except ValueError as e:
            return Response({"error": str(e)}, status=status.HTTP_500_INTERNAL_SERVER_ERROR)

# The rest of the AI logic was moved to services.py

@extend_schema_view(
    get=extend_schema(
        tags=['Goals'],
        summary="List all goals",
        description="Get a list of all goals with optional filtering by status, search, tag, and date range.",
        responses={200: GoalListSerializer(many=True)}
    ),
    post=extend_schema(
        tags=['Goals'],
        summary="Create a new goal",
        description="Create a new goal with tasks.",
        request=GoalCreateSerializer,
        responses={201: GoalCreateSerializer}
    )
)
class GoalView(APIView):
    """
    API endpoint for CRUD operations on goals
    GET: List all goals with optional filtering
    POST: Create a new goal
    """
    permission_classes = [IsAuthenticated]

    def get(self, request):
        """
        Get list of goals with optional filtering
        Query params:
        - status: Filter by status (ToDo, InProgress, Completed)
        - search: Search in name and description
        - tag: Filter by tag
        - startDate: Filter by start date
        - endDate: Filter by end date
        """
        user = request.user
        goals = Goal.objects.filter(user=user)

        # Apply filters
        status_filter = request.query_params.get('status', None)
        search_query = request.query_params.get('search', None)
        tag_filter = request.query_params.get('tag', None)
        start_date_filter = request.query_params.get('startDate', None)
        end_date_filter = request.query_params.get('endDate', None)

        if status_filter:
            goals = goals.filter(status=status_filter)

        # Search by keyword
        if search_query:
            goals = goals.filter(
                Q(name__icontains=search_query) | 
                Q(description__icontains=search_query)
            )
        
        if tag_filter:
            goals = goals.filter(tag__contains=[tag_filter])

        if start_date_filter:
            goals = goals.filter(created_at__date__gte=start_date_filter)

        if end_date_filter:
            goals = goals.filter(created_at__date__lte=end_date_filter)

        serializer = GoalListSerializer(goals, many=True)
        return Response(serializer.data)

    def post(self, request):
        """
        Create a new goal
        Request body:
        {
            "name": "Goal name",
            "description": "Goal description",
            "deadline": "YYYY-MM-DD",
            "tag": "Goal tag"
        }
        """
        serializer = GoalCreateSerializer(data=request.data)
        if serializer.is_valid():
            serializer.save(user=request.user)
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

@extend_schema_view(
    get=extend_schema(
        tags=['Goals'],
        summary="Get goal by ID",
        description="Retrieve a specific goal with all its tasks.",
        responses={200: GoalDetailSerializer}
    ),
    patch=extend_schema(
        tags=['Goals'],
        summary="Update a goal",
        description="Partially update a goal's details and/or tasks.",
        request=GoalDetailSerializer,
        responses={200: GoalDetailSerializer}
    ),
    delete=extend_schema(
        tags=['Goals'],
        summary="Delete a goal",
        description="Delete a goal and all its associated tasks.",
        responses={204: None}
    )
)
class GoalDetailView(APIView):
    """
    API endpoint for CRUD operations on a single goal
    GET: Get a goal by ID
    PATCH: Partially update a goal by ID
    DELETE: Delete a goal by ID
    """
    permission_classes = [IsAuthenticated]

    def get_object(self, goal_id):
        return get_object_or_404(Goal, id=goal_id, user=self.request.user)

    def get(self, request, goal_id):
        """
        Get a goal by ID
        """
        goal = self.get_object(goal_id)
        serializer = GoalDetailSerializer(goal)
        return Response(serializer.data, status=status.HTTP_200_OK)

    def patch(self, request, goal_id):
        """
        Partially update a goal by ID
        Request body (all fields optional):
        {
            "name": "Goal name",
            "description": "Goal description",
            "deadline": "YYYY-MM-DD",
            "tag": ["tag1", "tag2"],
            "tasks": [{"id": 1, "name": "Updated task"}]
        }
        """
        goal = self.get_object(goal_id)
        serializer = GoalDetailSerializer(goal, data=request.data, partial=True)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_200_OK)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

    def delete(self, request, goal_id):
        """
        Delete a goal and associated tasks by ID
        """
        goal = self.get_object(goal_id)
        goal.delete()
        return Response(status=status.HTTP_204_NO_CONTENT)



@extend_schema_view(
    get=extend_schema(
        tags=['Tasks'],
        summary="Get a task",
        description="Retrieve a specific task by ID.",
        responses={200: TaskSerializer}
    ),
    patch=extend_schema(
        tags=['Tasks'],
        summary="Update a task",
        description="Update a task's status, name, deadline.",
        request=TaskSerializer,
        responses={200: TaskSerializer}
    ),
    delete=extend_schema(
        tags=['Tasks'],
        summary="Delete a task",
        description="Delete a specific task from a goal.",
        responses={204: None}
    )
)
class TaskDetailView(APIView):
    """
    API endpoint for CRUD operations on an individual task
    GET: Retrieve a task by ID
    PATCH: Update a task (quick status/name changes)
    DELETE: Delete a task
    """
    permission_classes = [IsAuthenticated]
    
    def get_object(self, pk):
        return get_object_or_404(Task, pk=pk, goal__user=self.request.user)

    def get(self, request, pk):
        """
        Retrieve a task by ID
        URL: GET /v1/tasks/{taskId}
        """
        task = self.get_object(pk)
        serializer = TaskSerializer(task)
        return Response(serializer.data, status=status.HTTP_200_OK)
    
    def patch(self, request, pk):
        """
        Update a task's status, name, or other attributes
        URL: PATCH /v1/tasks/{taskId}
        """
        task = self.get_object(pk)
        serializer = TaskSerializer(task, data=request.data, partial=True)
        
        if serializer.is_valid():
            # Auto-set complete_date when status is changed to Completed
            if serializer.validated_data.get('status') == 'Completed' and task.status != 'Completed':
                serializer.validated_data['complete_date'] = timezone.now().date()
            
            serializer.save()
            return Response(serializer.data, status=status.HTTP_200_OK)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

    def delete(self, request, pk):
        """
        Delete a task
        URL: DELETE /v1/tasks/{taskId}
        """
        task = self.get_object(pk)
        task.delete()
        return Response(status=status.HTTP_204_NO_CONTENT)


@extend_schema_view(
    get=extend_schema(
        tags=['Tasks'],
        summary="List all tasks",
        description="Get all tasks for the authenticated user with optional filtering by status, goal_id, and search.",
        responses={200: TaskSerializer(many=True)}
    ),
    post=extend_schema(
        tags=['Tasks'],
        summary="Create a new task",
        description="Create a new task under a specific goal. The goal must belong to the authenticated user.",
        request=TaskSerializer,
        responses={201: TaskSerializer}
    )
)
class TaskListView(APIView):
    """
    API endpoint for task collection
    GET: List all tasks with optional filtering
    POST: Create a new task under a specific goal
    """
    permission_classes = [IsAuthenticated]

    def get(self, request):
        """
        Get list of all tasks with optional filtering
        Query params:
        - status: Filter by status (ToDo, InProgress, Completed)
        - goal_id: Filter by specific goal
        - search: Search in task name
        """
        # Get all tasks from user's goals
        tasks = Task.objects.filter(goal__user=request.user)

        # Apply filters
        status_filter = request.query_params.get('status', None)
        goal_id_filter = request.query_params.get('goalId', None)
        search_query = request.query_params.get('search', None)

        if status_filter:
            tasks = tasks.filter(status=status_filter)

        if goal_id_filter:
            tasks = tasks.filter(goal_id=goal_id_filter)

        if search_query:
            tasks = tasks.filter(name__icontains=search_query)

        # Order by deadline (soonest first), with tasks lacking a deadline placed after those with one
        from django.db.models.functions import Coalesce
        from django.db.models import Value
        from datetime import date
        tasks = tasks.select_related('goal').order_by(
            Coalesce('deadline', Value(date.max)),
            'created_at'
        )

        serializer = TaskSerializer(tasks, many=True)
        
        # Add goal_name to each task for context (using camelCase for API consistency)
        data = serializer.data
        for i, task in enumerate(tasks):
            data[i]['goalName'] = task.goal.name
            data[i]['goalId'] = str(task.goal.id)

        return Response(data)

    def post(self, request):
        """
        Create a new task under a specific goal.
        Request body:
        {
            "goal_id": "<uuid>",   # required - must belong to the current user
            "name": "Task name",
            "deadline": "YYYY-MM-DD",
            "status": "ToDo"        # optional, defaults to ToDo
        }
        """
        goal_id = request.data.get('goal_id')
        if not goal_id:
            return Response(
                {"goal_id": "This field is required."},
                status=status.HTTP_400_BAD_REQUEST
            )

        # Security: ensure the goal belongs to the current user
        goal = get_object_or_404(Goal, id=goal_id, user=request.user)

        serializer = TaskSerializer(data=request.data)
        if serializer.is_valid():
            serializer.save(goal=goal)
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)