from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status
from rest_framework.permissions import IsAuthenticated
from django.shortcuts import get_object_or_404
from django.db.models import Q
from drf_spectacular.utils import extend_schema, extend_schema_view
import os
import json
from together import Together
import dotenv
from pathlib import Path
import re
from openai import OpenAI
from django.utils import timezone

from .models import Goal, Task
from .serializers import (
    GoalListSerializer, 
    GoalDetailSerializer, 
    GoalCreateSerializer,
    TaskSerializer,
    GoalGenerateRequestSerializer,
    GoalGenerateResponseSerializer,
    MessageResponseSerializer
)

BASE_DIR = Path(__file__).resolve().parent.parent.parent
dotenv.load_dotenv(os.path.join(BASE_DIR, '.env'))

@extend_schema(
    tags=['Goals'], 
    auth=[],
    request=GoalGenerateRequestSerializer,
    responses={200: GoalGenerateResponseSerializer},
    summary="Generate goal with AI-powered task breakdown",
    description="Takes a goal's name, description, tag, and deadline, and returns a list of actionable tasks generated by AI."
)
class GoalBreakdownView(APIView):
    """
    API endpoint that takes a goal's name, description, tag, and deadline,
    and returns a list of actionable tasks to achieve that goal using the Groq API."""
    def post(self, request):
        name = request.data.get('name')
        description = request.data.get('description')
        tag = request.data.get('tag')
        deadline = request.data.get('deadline')

        if not name:
            return Response({"error": "Please provide a goal's name"}, status=status.HTTP_400_BAD_REQUEST)
        
        if not description:
            return Response({"error": "Please provide a goal's description"}, status=status.HTTP_400_BAD_REQUEST)
        
        if not deadline:
            return Response({"error": "Please provide a goal's deadline"}, status=status.HTTP_400_BAD_REQUEST)

        if deadline < timezone.now().date().isoformat():
            return Response({"error": "Deadline must be a future date"}, status=status.HTTP_400_BAD_REQUEST)
        # if not tag:
        #     return Response({"error": "Please provide a goal's tag"}, status=status.HTTP_400_BAD_REQUEST)

        api_key = self.get_api_key()
        if not api_key:
            return Response({"error": "Together AI API Key is not configured."}, status=status.HTTP_500_INTERNAL_SERVER_ERROR)
        task_prompt = self.build_prompt_for_task(name, description, deadline)
        description_prompt = self.build_prompt_for_description(name, description, deadline)
        task_list = self.get_ai_response(task_prompt, api_key)

        description_response = self.get_ai_response(description_prompt, api_key)
        
        # FIX: Check if it is ALREADY a list before trying to parse
        if isinstance(description_response, list):
            # It's already a list, just take the first item
            if description_response:
                description = description_response[0]
            else:
                description = "" # Handle empty list case
        else:
            # It is a string, so NOW we try to parse it
            try:
                parsed_description = json.loads(description_response)
                
                if isinstance(parsed_description, list) and parsed_description:
                    description = parsed_description[0]
                else:
                    description = str(parsed_description)
                    
            except (json.JSONDecodeError, TypeError):
                # Fallback: It was just a plain string all along
                description = description_response

        try:
            result = {}
            result["name"] = name
            result["description"] = description
            result["status"] = "ToDo"
            result["deadline"] = deadline
            result["tag"] = tag
            result["completeCount"] = 0
            result["taskCount"] = len(task_list)
            result["tasks"] = task_list
            return Response(result, status=status.HTTP_200_OK)
        except ValueError as e:
            return Response({"error": str(e)}, status=status.HTTP_500_INTERNAL_SERVER_ERROR)

    def get_api_key(self):
        return os.getenv("API_KEY")

    def get_ai_response(self, prompt, api_key, max_retries=3):
        """Get AI response with retry logic for network issues"""
        import time
        import httpx
        
        GROQ_MODEL = "groq/compound"
        
        for attempt in range(max_retries):
            try:
                client = OpenAI(
                    api_key=api_key,
                    base_url="https://api.groq.com/openai/v1",
                    timeout=60.0  # 60 second timeout
                )
                response_stream = client.chat.completions.create(
                    model=GROQ_MODEL,
                    messages=[
                        {"role": "system",
                            "content": "You are a helpful project management assistant."},
                        {"role": "user", "content": prompt}
                    ],
                    stream=True,
                    temperature=0.7
                )
                full_content = ""
                for chunk in response_stream:
                    if hasattr(chunk, 'choices') and chunk.choices and chunk.choices[0].delta.content is not None:
                        full_content += chunk.choices[0].delta.content
                        
                if not full_content:
                    raise ValueError("No response received from AI.")

                return self.extract_json_response(full_content)
                
            except (httpx.RemoteProtocolError, httpx.ReadTimeout, ConnectionError) as e:
                if attempt < max_retries - 1:
                    wait_time = (attempt + 1) * 2  # 2, 4, 6 seconds
                    time.sleep(wait_time)
                    continue
                else:
                    raise ValueError(f"AI service unavailable after {max_retries} attempts. Please try again later. Error: {str(e)}")

    def extract_json_response(self, text):
        # \s* means "zero or more whitespace characters."
        match = re.search(r"\[\s*[\s\S]*?\]", text)
        if match:
            json_array_response = match.group(0)
            try:
                tasks = json.loads(json_array_response)
                if not isinstance(tasks, list):
                    raise ValueError(
                        "AI did not return a JSON array as expected.")
                return tasks
            except (json.JSONDecodeError, ValueError):
                raise ValueError(
                    f"AI returned invalid format. Extracted: {json_array_response}")
        else:
            raise ValueError(
                f"Could not find a JSON array in AI response. Content: {text}")
            
    def build_prompt_for_task(self, name, description, deadline):
        return (
            f"""You are an excellent project management assistant.
            Here is a new goal:
            Name: '{name}'
            Description: '{description}'
            Deadline: '{deadline}'
            Please help me break down this goal name and description into specific, actionable steps from {timezone.now().date().isoformat()} to "{deadline}".
            Each step should be a clear, achievable task within deadline.
            
            Must return the list of tasks as a JSON array of strings.
            
            The return language should match the name and description language.
            
            Example:
            If the name is "Complete a graduation project on Fanpage Management" and description is "A project to manage a fanpage for a product" and deadline is "2023-12-31" and start date is "2023-09-29", return the result in the following format:
            
            [
                {{
                    "name": "Design Database",
                    "status": "ToDo",
                    "deadline": "2023-10-01",
                }}, 
                {{
                    "name": "Build API Login",
                    "status": "ToDo",
                    "deadline": "2023-10-15",
                }}, 
                {{  
                    "name": "Integrate Facebook API",
                    "status": "ToDo",
                    "deadline": "2023-11-01",
                }},
                {{
                    "name": "Build management interface",
                    "status": "ToDo",
                    "deadline": "2023-11-15",
                }},
                {{
                    "name": "Test and fix bugs",
                    "status": "ToDo",
                    "deadline": "2023-12-15",
                }},
                {{
                    "name": "Write report and prepare presentation",
                    "status": "ToDo",
                    "deadline": "2023-12-31",
                }}
            ]
            """
        )
    
    def build_prompt_for_description(self, name, description, deadline):
        return (
            f"""You are an excellent project management assistant.
            Here is a new goal:
            Name: '{name}'
            Description: '{description}'
            Deadline: '{deadline}'
            Please help me rewrite the goal description in a summary to just understand the context with expected outcomes not so detailed.
            
            Must return the rewritten description as a string inside a JSON array.
            
            The return language should match the name and description language.
            """
        )

@extend_schema_view(
    get=extend_schema(
        tags=['Goals'],
        summary="List all goals",
        description="Get a list of all goals with optional filtering by status, search, tag, and date range.",
        responses={200: GoalListSerializer(many=True)}
    ),
    post=extend_schema(
        tags=['Goals'],
        summary="Create a new goal",
        description="Create a new goal with tasks.",
        request=GoalCreateSerializer,
        responses={201: GoalCreateSerializer}
    )
)
class GoalView(APIView):
    """
    API endpoint for CRUD operations on goals
    GET: List all goals with optional filtering
    POST: Create a new goal
    """
    permission_classes = [IsAuthenticated]

    def get(self, request):
        """
        Get list of goals with optional filtering
        Query params:
        - status: Filter by status (ToDo, InProgress, Completed)
        - search: Search in name and description
        - tag: Filter by tag
        - start_date: Filter by start date
        - end_date: Filter by end date
        """
        user = request.user
        goals = Goal.objects.filter(user=user)

        # Apply filters
        status_filter = request.query_params.get('status', None)
        search_query = request.query_params.get('search', None)
        tag_filter = request.query_params.get('tag', None)
        start_date_filter = request.query_params.get('start_date', None)
        end_date_filter = request.query_params.get('end_date', None)

        if status_filter:
            goals = goals.filter(status=status_filter)

        # Search by keyword
        if search_query:
            goals = goals.filter(
                Q(name__icontains=search_query) | 
                Q(description__icontains=search_query)
            )
        
        if tag_filter:
            goals = goals.filter(tag__contains=[tag_filter])

        if start_date_filter:
            goals = goals.filter(created_at__date__gte=start_date_filter)

        if end_date_filter:
            goals = goals.filter(created_at__date__lte=end_date_filter)

        serializer = GoalListSerializer(goals, many=True)
        return Response(serializer.data)

    def post(self, request):
        """
        Create a new goal
        Request body:
        {
            "name": "Goal name",
            "description": "Goal description",
            "deadline": "YYYY-MM-DD",
            "tag": "Goal tag"
        }
        """
        serializer = GoalCreateSerializer(data=request.data)
        if serializer.is_valid():
            serializer.save(user=request.user)
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

@extend_schema_view(
    get=extend_schema(
        tags=['Goals'],
        summary="Get goal by ID",
        description="Retrieve a specific goal with all its tasks.",
        responses={200: GoalDetailSerializer}
    ),
    patch=extend_schema(
        tags=['Goals'],
        summary="Update a goal",
        description="Partially update a goal's details and/or tasks.",
        request=GoalDetailSerializer,
        responses={200: GoalDetailSerializer}
    ),
    delete=extend_schema(
        tags=['Goals'],
        summary="Delete a goal",
        description="Delete a goal and all its associated tasks.",
        responses={204: None}
    )
)
class GoalDetailView(APIView):
    """
    API endpoint for CRUD operations on a single goal
    GET: Get a goal by ID
    PATCH: Partially update a goal by ID
    DELETE: Delete a goal by ID
    """
    permission_classes = [IsAuthenticated]

    def get_object(self, goal_id):
        return get_object_or_404(Goal, id=goal_id, user=self.request.user)

    def get(self, request, goal_id):
        """
        Get a goal by ID
        """
        goal = self.get_object(goal_id)
        serializer = GoalDetailSerializer(goal)
        return Response(serializer.data, status=status.HTTP_200_OK)

    def patch(self, request, goal_id):
        """
        Partially update a goal by ID
        Request body (all fields optional):
        {
            "name": "Goal name",
            "description": "Goal description",
            "deadline": "YYYY-MM-DD",
            "tag": ["tag1", "tag2"],
            "tasks": [{"id": 1, "name": "Updated task"}]
        }
        """
        goal = self.get_object(goal_id)
        serializer = GoalDetailSerializer(goal, data=request.data, partial=True)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_200_OK)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

    def delete(self, request, goal_id):
        """
        Delete a goal and associated tasks by ID
        """
        goal = self.get_object(goal_id)
        goal.delete()
        return Response({"message": "Goal deleted successfully"}, status=status.HTTP_204_NO_CONTENT)

@extend_schema_view(
    patch=extend_schema(
        tags=['Tasks'],
        summary="Update a task",
        description="Update a task's status, name, deadline, or position.",
        request=TaskSerializer,
        responses={200: TaskSerializer}
    ),
    delete=extend_schema(
        tags=['Tasks'],
        summary="Delete a task",
        description="Delete a specific task from a goal.",
        responses={204: None}
    )
)
class TaskDetailView(APIView):
    """
    API endpoint for updating individual tasks
    PATCH: Update a task (quick status/name changes)
    DELETE: Delete a task
    """
    permission_classes = [IsAuthenticated]
    
    def get_object(self, pk, user):
        return get_object_or_404(Task, pk=pk, goal__user=user)
    
    def patch(self, request, goal_id, pk):
        """
        Update a task's status, name, or other attributes
        URL: PATCH /goals/<goal_id>/tasks/<task_id>
        """
        task = self.get_object(pk, request.user)
        serializer = TaskSerializer(task, data=request.data, partial=True)
        
        if serializer.is_valid():
            # Auto-set complete_date when status is changed to Completed
            if serializer.validated_data.get('status') == 'Completed' and task.status != 'Completed':
                serializer.validated_data['complete_date'] = timezone.now().date()
            
            serializer.save()
            return Response(serializer.data, status=status.HTTP_200_OK)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

    def delete(self, request, goal_id, pk):
        """
        Delete a task
        URL: DELETE /v1/goals/{goal_id}/tasks/{pk}
        """
        task = self.get_object(pk, request.user)
        task.delete()
        return Response(status=status.HTTP_204_NO_CONTENT)


@extend_schema_view(
    get=extend_schema(
        tags=['Tasks'],
        summary="List all tasks",
        description="Get all tasks for the authenticated user with optional filtering by status, goal_id, and search.",
        responses={200: TaskSerializer(many=True)}
    )
)
class TaskListView(APIView):
    """
    API endpoint to list all tasks for the authenticated user
    GET: List all tasks with optional filtering
    """
    permission_classes = [IsAuthenticated]

    def get(self, request):
        """
        Get list of all tasks with optional filtering
        Query params:
        - status: Filter by status (ToDo, InProgress, Completed)
        - goal_id: Filter by specific goal
        - search: Search in task name
        """
        # Get all tasks from user's goals
        tasks = Task.objects.filter(goal__user=request.user)

        # Apply filters
        status_filter = request.query_params.get('status', None)
        goal_id_filter = request.query_params.get('goal_id', None)
        search_query = request.query_params.get('search', None)

        if status_filter:
            tasks = tasks.filter(status=status_filter)

        if goal_id_filter:
            tasks = tasks.filter(goal_id=goal_id_filter)

        if search_query:
            tasks = tasks.filter(name__icontains=search_query)

        # Order by deadline (soonest first)
        tasks = tasks.select_related('goal').order_by('deadline', 'position')

        serializer = TaskSerializer(tasks, many=True)
        
        # Add goal_name to each task for context
        data = serializer.data
        for i, task in enumerate(tasks):
            data[i]['goal_name'] = task.goal.name
            data[i]['goal_id'] = task.goal.id

        return Response(data)